CREATE TABLE EXAMINED (
  GENOTYPE INTEGER NOT NULL PRIMARY KEY,
  CLASS VARCHAR(2)
);

CREATE TABLE FLAGELLA (
  ALPHA INTEGER,
  BETA INTEGER,
  NUMBER INTEGER
);

CREATE TABLE TOUGHNESS (
  BETA INTEGER,
  GAMMA INTEGER,
  RANK CHAR(1)
);
